# Generated by Django 3.2.20 on 2024-09-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20240906_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='date_of_biirth',
            new_name='date_of_birth',
        ),
    ]
